apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cbioagent
spec:
  project: default
  sources:
#    - repoURL: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment
#      path: argocd/aws/203403084713/clusters/cbioportal-prod/apps/cbioagent
#      targetRevision: HEAD
#      directory:
#        recurse: true
#      ref: k8s-repo
    - path: helm/librechat
      repoURL: https://github.com/danny-avila/LibreChat.git
      targetRevision: HEAD
      helm:
        releaseName: cbioagent
        valueFiles:
          - values.yaml
#          - $k8/argocd/aws/203403084713/clusters/cbioportal-prod/apps/datadog/values.yaml
  destination:
    namespace: default
    server: https://kubernetes.default.svc