apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
spec:
  project: default
  sources:
    - repoURL: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment
      path: argocd/aws/203403084713/clusters/cbioportal-prod/apps/datadog
      targetRevision: HEAD
      directory:
        recurse: true
      ref: datadog
    - repoURL: https://helm.datadoghq.com
      targetRevision: 3.97.0
      chart: datadog
      helm:
        releaseName: datadog
        valueFiles:
          - $datadog/argocd/aws/203403084713/clusters/cbioportal-prod/apps/datadog/values.yaml
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true