apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oncokb
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment
      path: argocd/aws/203403084713/clusters/cbioportal-prod/apps/oncokb
      targetRevision: HEAD
      directory:
        recurse: true
      ref: k8s-repo
    - repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 8.4.0
      chart: redis-cluster
      helm:
        releaseName: oncokb-redis-cluster-ng
        valueFiles:
          - $k8s-repo/argocd/aws/203403084713/clusters/cbioportal-prod/apps/oncokb/values.yaml
    - repoURL: https://codecentric.github.io/helm-charts
      targetRevision: 18.4.4
      chart: keycloak
      helm:
        releaseName: oncokb-keycloak
        valueFiles:
          - $k8s-repo/argocd/aws/203403084713/clusters/cbioportal-prod/apps/oncokb/keycloak/values.yaml
    # - repoURL: https://airflow-helm.github.io/charts
    #   targetRevision: 8.9.0
    #   chart: airflow
    #   helm:
    #     releaseName: oncokb-airflow
    #     valueFiles:
    #       - $k8s-repo/argocd/aws/203403084713/clusters/cbioportal-prod/apps/oncokb/airflow/values.yaml
    - repoURL: https://mrnim94.github.io/redisinsight/
      targetRevision: 1.3.1
      chart: redisinsight
      helm:
        releaseName: redisinsight
        valueFiles:
          - $k8s-repo/argocd/aws/203403084713/clusters/cbioportal-prod/apps/oncokb/redisinsight/values.yaml
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 54.2.2
      chart: kube-prometheus-stack
      helm:
        releaseName: oncokb-kube-prometheus-stack
        valueFiles:
          - $k8s-repo/argocd/aws/203403084713/clusters/cbioportal-prod/apps/oncokb/kube-prometheus-stack/values.yaml
  destination:
    namespace: oncokb
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
