apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-session
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 20.8.0
    chart: redis
    helm:
      releaseName: cbioportal-redis-public
      # Parameters list: https://artifacthub.io/packages/helm/bitnami/redis#parameters
      fileParameters:
        - name: master
          path: redis-params.yaml
      parameters:
        - name: global.imagePullSecrets[0]
          value: dockerhub-creds
        - name: architecture
          value: standalone
        - name: auth.enabled
          value: "true"
        - name: auth.existingSecret
          value: cbioportal-public6
        - name: auth.existingSecretPasswordKey
          value: REDIS_SESSION_PASSWORD
        - name: master.persistence.enabled
          value: "false"
        - name: replica.persistence.enabled
          value: "false"
        - name: master.extraFlags[0]
          value: --maxmemory 8gb
        - name: master.extraFlags[1]
          value: --maxmemory-policy volatile-ttl
        - name: master.tolerations[0].key
          value: workload
        - name: master.tolerations[0].value
          value: cbioportal-redis
        - name: master.tolerations[0].operator
          value: Equal
        - name: master.tolerations[0].effect
          value: NoSchedule
  destination:
    namespace: default
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-persistence-cache
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 20.8.0
    chart: redis
    helm:
      releaseName: cbioportal-public-persistence-redis
      # Parameters list: https://artifacthub.io/packages/helm/bitnami/redis#parameters
      parameters:
        - name: global.imagePullSecrets[0]
          value: dockerhub-creds
        - name: architecture
          value: replication
        - name: auth.enabled
          value: "true"
        - name: auth.existingSecret
          value: cbioportal-public6
        - name: auth.existingSecretPasswordKey
          value: REDIS_PERSISTENCE_PASSWORD
        - name: master.persistence.enabled
          value: "false"
        - name: replica.persistence.enabled
          value: "false"
        - name: master.extraFlags[0]
          value: --maxmemory 8gb
        - name: master.extraFlags[1]
          value: --maxmemory-policy volatile-ttl
        - name: master.nodeSelector.workload
          value: redis
        - name: master.tolerations[0].key
          value: workload
        - name: master.tolerations[0].value
          value: cbioportal-redis
        - name: master.tolerations[0].operator
          value: Equal
        - name: master.tolerations[0].effect
          value: NoSchedule
        - name: replica.replicaCount
          value: "2"
        - name: replica.autoscaling.enabled
          value: "true"
        - name: replica.autoscaling.minReplicas
          value: "2"
        - name: replica.autoScaling.maxReplicas
          value: "3"
        - name: replica.extraFlags[0]
          value: --maxmemory 8gb
        - name: replica.extraFlags[1]
          value: --maxmemory-policy volatile-ttl
        - name: replica.nodeSelector.workload
          value: redis
        - name: replica.tolerations[0].key
          value: workload
        - name: replica.tolerations[0].value
          value: cbioportal-redis
        - name: replica.tolerations[0].operator
          value: Equal
        - name: replica.tolerations[0].effect
          value: NoSchedule
  destination:
    namespace: default
    server: https://kubernetes.default.svc