apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8888
  selector:
    run: {{ .Values.name }}
  type: ClusterIP
