apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment
      path: argocd/aws/084637913395/clusters/oncokb-production/apps/ingress
      targetRevision: HEAD
      directory:
        recurse: true
      ref: k8s-repo
    - repoURL: https://github.com/kubernetes/ingress-nginx.git
      targetRevision: 4.12.1
      path: charts/ingress-nginx
      helm:
        releaseName: oncokb-ingress-nginx
        valueFiles:
          - $k8s-repo/argocd/aws/084637913395/clusters/oncokb-production/apps/ingress/values.yaml
  destination:
    namespace: default
    server: https://kubernetes.default.svc