apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  project: default
  sources:
    - repoURL: https://github.com/prometheus-community/helm-charts.git
      targetRevision: kube-prometheus-stack-54.2.2
      path: charts/kube-prometheus-stack
      helm:
        releaseName: kube-prometheus-stack
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true