apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-05-05T06:32:48Z"
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: genie-genome-nexus
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  machineType: t3.xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: genie-genome-nexus
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-12-09T21:11:58Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: genie-portals
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  machineType: r5.xlarge
  maxSize: 4
  minSize: 4
  nodeLabels:
    kops.k8s.io/instancegroup: genie-portals
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-11-19T14:49:29Z"
  generation: 16
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: genome-nexus
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  machineType: t3.xlarge
  maxSize: 4
  minSize: 4
  nodeLabels:
    kops.k8s.io/instancegroup: genome-nexus
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-05-05T04:53:04Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: gnap-genome-nexus
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  machineType: t3.xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: gnap-genome-nexus
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-10-24T21:18:37Z"
  generation: 27
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: large-mem
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  machineType: r5.xlarge
  maxSize: 5
  minSize: 4
  nodeLabels:
    kops.k8s.io/instancegroup: large-mem
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-08-06T18:29:31Z"
  generation: 8
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: master-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-05-05T05:08:34Z"
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: master-us-east-1b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1b
  role: Master
  subnets:
  - us-east-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-05-05T05:08:44Z"
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: master-us-east-1c
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1c
  role: Master
  subnets:
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-03-30T21:50:55Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: mission-critical
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  machineType: r5.xlarge
  maxSize: 3
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: mission-critical
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c
  taints:
  - dedicated=mission-critical:NoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-08-06T18:29:31Z"
  generation: 6
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: nodes
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  machineType: t2.medium
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2023-03-16T17:36:46Z"
  generation: 4
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: oncokb
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  machineType: r5.2xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: oncokb
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c
  taints:
  - dedicated=oncokb:NoSchedule

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-07-02T20:34:53Z"
  generation: 6
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: redis-persistence-cache
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230302
  machineType: r5.xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: redis-persistence-cache
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c
