apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-10-30T18:22:17Z"
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: cbioportal-performance-testing
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2020-07-20
  machineType: r5.xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: cbioportal-performance-testing
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-03-19T15:46:42Z"
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: genie-genome-nexus
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t2.xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: genie-genome-nexus
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-12-09T21:11:58Z"
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: genie-portals
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2020-11-19
  machineType: r5.xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: genie-portals
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-11-19T14:49:29Z"
  generation: 13
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: genome-nexus
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t3.xlarge
  maxSize: 5
  minSize: 5
  nodeLabels:
    kops.k8s.io/instancegroup: genome-nexus
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-07-16T18:46:49Z"
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: genome-nexus-angelica-test
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: genome-nexus-angelica-test
  role: Node
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-06-15T20:00:57Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: gnap-genome-nexus
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t3.xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: gnap-genome-nexus
  role: Node
  subnets:
  - us-east-1c
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-02-12T09:45:50Z"
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: indispensable
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2020-11-19
  machineType: t2.small
  maxSize: 2
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: indispensable
  role: Node
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-10-24T21:18:37Z"
  generation: 25
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: large-mem
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: r5.xlarge
  maxSize: 5
  minSize: 4
  nodeLabels:
    kops.k8s.io/instancegroup: large-mem
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-08-06T18:29:31Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-08-06T18:29:31Z"
  generation: 2
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: t2.medium
  maxSize: 4
  minSize: 4
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-10-15T13:15:43Z"
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: redis-cache
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2020-07-20
  machineType: r5.xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: redis-cache
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-07-02T20:34:53Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: redis-persistence-cache
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: r5.xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: redis-persistence-cache
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c
