apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: null
  generation: 1
  labels:
    run: oncotree
  name: oncotree
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/oncotree
spec:
  replicas: 1
  selector:
    matchLabels:
      run: oncotree
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: oncotree
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: oncotree-eks
        image: mandaewilson/oncotree:oncotree
        command: [ "java" ]
        args: ["-Dspringfox.documentation.swagger.v2.path=/api-docs",
        "-Dserver.port=8080",
        "-Dtopbraid.url=http://test.evn.mskcc.org/edg/tbl/sparql",
        "-Dtopbraid.username=$(TOPBRAID_USERNAME)",
        "-Dtopbraid.password=$(TOPBRAID_PASSWORD)",
        "-Dtopbraid.oncotree_namespace_prefix=http://data.mskcc.org/ontologies/oncotree#",
        "-Dtopbraid.oncotree_version_namespace_prefix=http://data.mskcc.org/ontologies/OncoTreeVersion#",
        "-Dtopbraid.oncotree_version_list_graph_id=urn:x-evn-master:oncotreeversionlist",
        "-Dslack.url=$(SLACK_URL)",
        "-Dslack.channel=msk-pipeline-logs",
        "-Drequired.oncotree.version=oncotree_latest_stable",
        "-jar", 
        "oncotree.jar"]
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 100
          timeoutSeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 10
          periodSeconds: 1
          failureThreshold: 5
        name: oncotree
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
              cpu: 100m
              memory: 1Gi
          limits:
              memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      # run on big memory machine
      nodeSelector:
        eks.amazonaws.com/nodegroup: essential-services
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: oncotree
  name: oncotree
  selfLink: /api/v1/namespaces/default/services/oncotree
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    run: oncotree
  type: ClusterIP
