apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cbioportal
  namespace: argocd
spec:
  project: default
  sources:
    - path: argocd/aws/666628074417/clusters/cbioportal-prod/apps/cbioportal
      repoURL: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment
      targetRevision: HEAD
      directory:
        recurse: true
  destination:
    namespace: default
    server: https://kubernetes.default.svc