apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oncokb-ingress
  namespace: oncokb
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/limit-rps: "100"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    # the following has to be added due to an issue of from-to-www-redirect. https://github.com/kubernetes/ingress-nginx/issues/2043
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = 'oncokb.org' ) {
        rewrite ^ https://www.oncokb.org$request_uri permanent;
      }
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    ingress.kubernetes.io/proxy-connect-timeout: "300"
    ingress.kubernetes.io/proxy-read-timeout: "300"
    ingress.kubernetes.io/proxy-send-timeout: "300"
    # ingress.kubernetes.io/large-client-header-buffers: "4 32k"
    # increae max response size to avoid 413 errors see
    # https://github.com/kubernetes/ingress-nginx/issues/1824
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    ingress.kubernetes.io/proxy-body-size: 512m
    # add proxy protocol to header
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
spec:
  tls:
  # we need to keep the oncokb.org in the tls list so the SSL cert includes the domain so after forwarding, it would not have SSL cert error
  - hosts:
    - oncokb.org
    - www.oncokb.org
    - beta.oncokb.org
    - beta.core.oncokb.org
    - legacy.oncokb.org
    - test.oncokb.org
    - demo.oncokb.org
    - sop.oncokb.org
    - msk.oncokb.org
    - public.api.oncokb.org
    - transcript.oncokb.org
    - beta.transcript.oncokb.org
    - curation.oncokb.org
    - keycloak.oncokb.org
    - grafana.oncokb.org
    - airflow.oncokb.org
    secretName: oncokb-cert
  rules:
  # we have to keep the oncokb.org entry because of the from-to-www-redirect issue above
  - host: oncokb.org
    http:
      paths:
      - path: /
        backend:
          serviceName: oncokb-public
          servicePort: http
  - host: www.oncokb.org
    http:
      paths:
      - path: /
        backend:
          serviceName: oncokb-public
          servicePort: http
  - host: beta.oncokb.org
    http:
      paths:
      - path: /
        backend:
          serviceName: oncokb-public-beta
          servicePort: http
  - host: beta.core.oncokb.org
    http:
      paths:
      - path: /
        backend:
          serviceName: oncokb-core-beta
          servicePort: 8888
  - host: demo.oncokb.org
    http:
      paths:
      - path: /
        backend:
          serviceName: oncokb-core-demo
          servicePort: http
  - host: test.oncokb.org
    http:
      paths:
      - path: /
        backend:
          serviceName: oncokb-transcript-test
          servicePort: http
  - host: legacy.oncokb.org
    http:
      paths:
      - path: /
        backend:
          serviceName: oncokb-core-legacy
          servicePort: http
  - host: sop.oncokb.org
    http:
      paths:
      - path: /
        backend:
          serviceName: oncokb-sop
          servicePort: http
  - host: msk.oncokb.org
    http:
      paths:
      - path: /
        backend:
          serviceName: oncokb-public
          servicePort: http
  - host: transcript.oncokb.org
    http:
      paths:
        - path: /
          backend:
            serviceName: oncokb-transcript
            servicePort: http
  - host: beta.transcript.oncokb.org
    http:
      paths:
        - path: /
          backend:
            serviceName: oncokb-transcript-beta
            servicePort: http
  - host: curation.oncokb.org
    http:
      paths:
        - path: /
          backend:
            serviceName: oncokb-curation
            servicePort: http
  - host: keycloak.oncokb.org
    http:
      paths:
        - path: /
          backend:
            serviceName: oncokb-keycloak-http
            servicePort: http
  - host: public.api.oncokb.org
    http:
      paths:
      - path: /
        backend:
          serviceName: oncokb-core-public
          servicePort: http
  - host: grafana.oncokb.org
    http:
      paths:
      - path: /
        backend:
          serviceName: oncokb-grafana
          servicePort: 80
  - host: airflow.oncokb.org
    http:
      paths:
      - path: /
        backend:
          serviceName: oncokb-airflow-ng
          servicePort: 8080
