grafana:
  admin:
    existingSecret: "grafana-admin"
    userKey: ADMIN_USER
    passwordKey: ADMIN_PASSWORD
  nodeSelector:
    workload: lg-general

prometheus:
  prometheusSpec:
    nodeSelector:
      workload: lg-general

kubeStateMetrics:
  nodeSelector:
    workload: lg-general

nodeExporter:
  nodeSelector:
    workload: lg-general

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      workload: lg-general