apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: null
  generation: 1
  labels:
    run: eks-cdd
  name: eks-cdd
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/eks-cdd
spec:
  replicas: 1
  selector:
    matchLabels:
      run: eks-cdd
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: eks-cdd
    spec:
      volumes:
      - name: cdd-ssl-volume
        configMap:
          name: cdd-ssl
          items:
          - key: AwsSsl-truststore
            path: AwsSssl-truststore
      - name: cdd-cache
        persistentVolumeClaim:
          claimName: cdd-pvc
      containers:
      - envFrom:
        - configMapRef:
            name: cdd-eks
        image: cbioportal/cdd:211130
        command: [ "java" ]
        args: ["-Dtopbraid.knowledgeSystems.serviceUrl=https://evn.mskcc.org/edg/tbl/sparql",
	"-Djavax.net.ssl.trustStore=/cdd-ssl/AwsSsl.truststore",
	"-Djavax.net.ssl.trustStorePassword=$(AWS_TRUSTSTORE_PASSWORD)",
        "-Dtopbraid.knowledgeSystems.loginUrl=https://evn.mskcc.org/edg/tbl/sparql",
        "-Dtopbraid.knowledgeSystems.username=$(TOPBRAID_USERNAME)",
        "-Dtopbraid.knowledgeSystems.password=$(TOPBRAID_PASSWORD)",
        "-Dtopbraid.knowledgeSystems.cddNamespacePrefix=http://data.mskcc.org/ontologies/ClinicalDataDictionary#",
        "-Dtopbraid.knowledgeSystems.cddGraphId=urn:x-evn-master:cdd",
        "-Dtopbraid.mskVocabulary.serviceUrl=https://evn.mskcc.org/edg/api/projects",
        "-Dtopbraid.mskVocabulary.loginUrl=https://evn.mskcc.org/edg/tbl/sparql",
        "-Dtopbraid.mskVocabulary.username=$(TOPBRAID_USERNAME)",
        "-Dtopbraid.mskVocabulary.password=$(TOPBRAID_PASSWORD)",
        "-Dslack.url=$(SLACK_URL)",
        "-DmskVocabulary.studyIdList=msk_extract_cohort2_2019",
        "-jar", 
        "cdd.jar"]
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /swagger-ui.html 
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 1
          failureThreshold: 5
        name: cdd
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: "/data/ehcache/"
          name: cdd-cache
        - name: cdd-ssl-volume
          mountPath: "/cdd-ssl/"
          subPath: AwsSsl-truststore
        resources:
          requests:
              cpu: 100m
              memory: 1Gi
          limits:
              memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      # run on big memory machine
      nodeSelector:
        eks.amazonaws.com/nodegroup: essential-services
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: eks-cdd
  name: eks-cdd
  selfLink: /api/v1/namespaces/default/services/eks-cdd
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    run: eks-cdd
  type: ClusterIP
