apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: cellxgene
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4180
          protocol: TCP
        args:
        - --provider=azure
        - --http-address=0.0.0.0:4180
        - --cookie-name=_oauth2_proxy_gbm
        - --cookie-domain=.cbioportal.org
        - --cookie-expire=0
        - --cookie-secure=true
        - --reverse-proxy=true
        - --whitelist-domain=.cbioportal.org
        - --email-domain=*
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-azure-provider
              key: client_id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-azure-provider
              key: client_secret
        - name: OAUTH2_PROXY_AZURE_TENANT
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-azure-provider
              key: azure_tenant
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-azure-provider
              key: oidc_issuer_url
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-azure-provider
              key: cookie_secret
      nodeSelector:
        workload: cellxgene
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "cellxgene"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy  
  name: oauth2-proxy
  namespace: cellxgene
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
