apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
spec:
  project: default
  sources:
    - repoURL: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment
      path: argocd/aws/762447640649/clusters/oncokb-dev/apps/keycloak
      targetRevision: HEAD
      directory:
        recurse: true
      ref: k8s-repo
    - repoURL: https://codecentric.github.io/helm-charts
      targetRevision: 14.0.0
      chart: keycloak
      helm:
        releaseName: oncokb-keycloak
        valueFiles:
          - $k8s-repo/argocd/aws/762447640649/clusters/oncokb-dev/apps/keycloak/values.yaml
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
