apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oncotree
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment
      path: argocd/aws/762447640649/clusters/oncokb-dev/oncotree
      targetRevision: HEAD
      directory:
        recurse: true
  destination:
    namespace: default
    server: https://kubernetes.default.svc