apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-cert
  namespace: monitoring
spec:
  # Secret names are always required.
  secretName: monitoring-cert
  dnsNames:
    - grafana.cbioportal.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
