master:
  extraFlags:
  - --maxmemory 8gb
  - --maxmemory-policy volatile-ttl
  nodeSelector:
    eks.amazonaws.com/nodegroup: essential-services
  persistence:
    enabled: false
  count: 2
replica:
  extraFlags:
  - --maxmemory 8gb
  - --maxmemory-policy volatile-ttl
  nodeSelector:
    eks.amazonaws.com/nodegroup: essential-services
  persistence:
    enabled: false
