apiVersion: batch/v1
kind: CronJob
metadata:
  name: cbioportal-public-mysqldump-weekly
spec:
  schedule: "59 23 * * 6"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - envFrom:
                - configMapRef:
                    name: aws-cli-credentials
                - configMapRef:
                    name: cbioportal-mysql-dump
              name: cbioportal-public-mysqldump-weekly
              image: mysql:8.0-debian
              command: ["/bin/sh", "-c"]
              args:
                - echo "Install curl";
                  apt-get update; apt-get install unzip curl less -y;
                  echo "Done installing curl\n\n";
                  
                  echo "Install aws cli";
                  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscli.zip";
                  unzip awscli.zip;
                  ./aws/install;
                  echo "Done installing aws cli\n\n";
                  
                  echo "Configure AWS CLI";
                  aws configure set aws_access_key_id ${ACCESS_KEY_ID};
                  aws configure set aws_secret_access_key ${SECRET_ACCESS_KEY};
                  aws configure set default.region ${AWS_REGION};
                  echo "Done configuring AWS CLI\n\n";

                  # Add date and current database version to file name
                  SCHEMA_VERSION=$(
                    mysql \
                    -h${DB_HOST} \
                    -u${DB_USER} \
                    -p"${DB_PASSWORD}" \
                    ${DB_PORTAL_DB_NAME} \
                    -s -N -e \
                    "select DB_SCHEMA_VERSION from info;" | sed "s/\./_/g"
                  );
                  
                  MYSQL_DUMP_FILE_NAME=dump_$(date "+%Y_%m_%d")_v${SCHEMA_VERSION}.sql.gz;

                  # Dump mysql database to s3 bucket
                  echo "Dump database to aws s3 bucket";
                  mysqldump \
                    -h${DB_HOST} \
                    -u${DB_USER} \
                    -p"${DB_PASSWORD}" \
                    --compress \
                    ${DB_PORTAL_DB_NAME} | \
                    gzip | \
                    aws s3 cp - s3://${AWS_S3_DUMP_BUCKET}/${MYSQL_DUMP_FILE_NAME};
                  echo "Done dumping to bucket\n\n";

                  # Delete objects older than 30 days
                  FILE_OLDER_THAN_30_DAYS=$(
                  aws s3api list-objects-v2 \
                  --bucket ${AWS_S3_DUMP_BUCKET} \
                  --query "Contents[?LastModified<'$(date -u -d '30 days ago' +%Y-%m-%dT%H:%M:%SZ)'].Key" \
                  --output text
                  );
                  
                  echo "Delete previous dumps that are older than a month";
                  aws s3 rm s3://${AWS_S3_DUMP_BUCKET}/${FILE_OLDER_THAN_30_DAYS};
                  echo "Done deleting older dumps\n\n";

          restartPolicy: OnFailure