## Configure Git to pull dags and plugins
git:
  dags:
    enabled: true
    repositories:
      # More information on getting DAG files from GitHub:
      # https://github.com/bitnami/charts/tree/main/bitnami/airflow#option-2-get-your-dag-files-from-a-git-repository
      - repository: https://oncokbdev:${ONCOKBDEV_PRIVATE_ACCESS_TOKEN}@github.com/oncokb/oncokb-pipeline
        branch: master
        name: oncokb-airflow-dags
        path: /oncokb-airflow
  clone:
    # Airflow runs an initContainer to clone the repository
    extraEnvVarsCM: oncokb-github
  sync:
    # By default airflow syncs with the repo every 60s.
    extraEnvVarsCM: oncokb-github

auth:
  username: admin

serviceAccount:
  name: "oncokb-airflow-service-account"

# Passing this to PYTHONPATH helps resolve some import errors in python files.
extraEnvVars:
  - name: PYTHONPATH
    value: "/opt/bitnami/airflow/dags/git_oncokb-airflow-dags/"