sentinel:
  enabled: true
  masterSet: oncokb-master
# For more eviction policy, please see https://docs.redislabs.com/latest/rs/administering/database-operations/eviction-policy/
master:
  extraFlags:
  - --maxmemory 5gb
  - --maxmemory-policy volatile-lfu
replica:
  extraFlags:
  - --maxmemory 5gb
  - --maxmemory-policy volatile-lfu