apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: null
  generation: 1
  labels:
    run: oncokb-core
  name: oncokb-core
  namespace: oncokb
  selfLink: /apis/extensions/v1beta1/namespaces/oncokb/deployments/oncokb-core
spec:
  replicas: 4
  selector:
    matchLabels:
      run: oncokb-core
  strategy:
    rollingUpdate:
      # We want to do a rolling updates to make sure all old instances removed before last new pod is initialized.
      maxSurge: 0
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: oncokb-core
    spec:
      containers:
        - env:
          envFrom:
            - configMapRef:
                name: oncokb-core
            - configMapRef:
                name: aws-cli-credentials
            - configMapRef:
                name: oncokb-github
          image: oncokb/oncokb:3.4.3
          command: ["java"]
          args: [
            # from https://developers.redhat.com/blog/2017/04/04/openjdk-and-containers/
            "-Xms250m",
            "-XX:+UseSerialGC",
            # aggressive garbage collection
            "-XX:MinHeapFreeRatio=20",
            "-XX:MaxHeapFreeRatio=40",
            "-XX:GCTimeRatio=4",
            "-XX:AdaptiveSizePolicyWeight=90",
            "-XX:+UnlockExperimentalVMOptions",
            "-XX:+UseCGroupMemoryLimitForHeap",
            # use maxRAMFraction > 1 https://github.com/akka/akka/issues/23499
            "-XX:MaxRAMFraction=2",
            "-XX:+PrintFlagsFinal",
            "-XshowSettings:vm",
            # need to set MaxRAM, somehow the MaxRAMFraction is not picked up
            # from the limits
            "-XX:MaxRAM=1024m",
            "-Dapp.name=$(APP_NAME)",
            "-Djdbc.driverClassName=com.mysql.jdbc.Driver",
            "-Djdbc.url=jdbc:mysql://$(DB_HOST):3306/$(MYSQL_DATABASE)?useUnicode=yes&characterEncoding=UTF-8&useSSL=false",
            "-Djdbc.username=$(MYSQL_USER)",
            "-Djdbc.password=$(MYSQL_PASSWORD)",
            "-Dgenomenexus.api=https://www.genomenexus.org/",
            "-Daws.s3.accessKey=$(ACCESS_KEY_ID)",
            "-Daws.s3.secretKey=$(SECRET_ACCESS_KEY)",
            "-Daws.s3.region=$(AWS_REGION)",
            "-Doncokb_data.access_token=$(ONCOKBDEV_PRIVATE_ACCESS_TOKEN)",
            "-Doncokb_transcript.token=$(ONCOKB_TRANSCRIPT_TOKEN)",
            "-Dredis.enable=$(REDIS_ENABLE)",
            "-Dredis.type=$(REDIS_TYPE)",
            "-Dredis.address=$(REDIS_ADDRESS)",
            "-Dredis.password=$(REDIS_PASSWROD)",
            "-Dredis.masterName=$(REDIS_MASTERNAME)",
            "-Dredis.expiration=$(REDIS_EXPIRATION)",
            "-Dshow_sitemaps=false",
            "-jar",
            "/webapp-runner.jar",
            "--enable-compression",
            "--expand-war",
            "--port",
            "8888",
            "/app.war"
          ]
          imagePullPolicy: Always
          # use actionable variants endpoint to cache everything
          readinessProbe:
            httpGet:
              path: /api/v1/utils/allActionableVariants
              port: 8888
            initialDelaySeconds: 15
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /api/v1/utils/allActionableVariants
              port: 8888
            # wait for the pod is ready
            initialDelaySeconds: 540
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 10
          name: oncokb-core
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 4Gi
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: oncokb-core
  name: oncokb-core
  namespace: oncokb
  selfLink: /api/v1/namespaces/oncokb/services/oncokb-core
spec:
  ports:
    - port: 8888
  selector:
    run: oncokb-core
  type: ClusterIP
