apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncokb-public-fda
  namespace: oncokb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oncokb-public-fda
      version: 'v1'
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oncokb-public-fda
        version: 'v1'
    spec:
      containers:
        - name: oncokb-public-fda
          image: oncokb/oncokb-public:3.0.5-fda.10
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod,no-liquibase
            - name: JAVA_OPTS
              value: '-Xmx1024m -Xms512m'
            - name: APPLICATION_REDIS_ADDRESS
              value: '$(REDIS_ADDRESS)'
            - name: APPLICATION_REDIS_PASSWORD
              value: '$(REDIS_PASSWROD)'
            - name: APPLICATION_REDIS_SENTINEL_MASTER_NAME
              value: '$(REDIS_MASTERNAME)'
          envFrom:
            - configMapRef:
                name: oncokb-public-fda
            - configMapRef:
                name: oncokb-sentinel-redis
          readinessProbe:
            httpGet:
              path: /v2/api-docs
              port: 9095
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 9095
            initialDelaySeconds: 90
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 5
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 2Gi
              cpu: 750m
          ports:
            - name: http
              containerPort: 9095

---
apiVersion: v1
kind: Service
metadata:
  name: oncokb-public-fda
  namespace: oncokb
  labels:
    app: oncokb-public-fda
spec:
  selector:
    app: oncokb-public-fda
  type: ClusterIP
  ports:
    - name: http
      port: 9095
