---
clusterName: "oncokb-elasticsearch"

antiAffinity: "soft"

esJavaOpts: "-Xms1g -Xmx1g"

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "gp2"
  resources:
    requests:
      storage: 15Gi
