apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mskanotheringress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "cbioportal.mskcc.org"
    http:
      paths:
      - path: "/mskcc(/|$)(.*)"
        pathType: Prefix
        backend:
          service:
            name: eks-msk
            port:
               number: 80
