apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: ingress
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-06-30T15:58:43Z"
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 0.47.0
    helm.sh/chart: ingress-nginx-3.34.0
  name: ingress-ingress-nginx-controller
  namespace: default
  resourceVersion: "8017287"
  selfLink: /api/v1/namespaces/default/configmaps/ingress-ingress-nginx-controller
  uid: ea0120af-f605-488e-b321-e8af31efbcfe
data:
  use-forwarded-headers: "true"
