# 1. AWS EKS role for S3 access instead of AWS_ACCESS_KEY or a SECRETS/Configmap setup
# Secrets for AWS Creds
# 2. Subdomain/Host for cellxgene resources cellxgene.cbioportal.org
# 3. Configmap for setting source bucket 
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cellxgene-deploy-1
  labels:
    app: cellxgene
    dataset: pbmc3k.h5ad
spec:
  replicas: 1
  selector:
    matchLabels:
      dataset: pbmc3k.h5ad
  template:
    metadata:
      labels:
        dataset: pbmc3k.h5ad
    spec:
      # serviceAccountName: cellxgene-service-account
      containers:
        - name: cellxgene-app
          image: 'edit01/cellxgene:1.2.0'
          command: ["cellxgene"]
          args: [
            "launch", 
            "-p", 
            "8080", 
            "--host", 
            "0.0.0.0", 
            "--backed", 
            "--disable-annotations", 
            "--disable-gene-sets-save", 
            "s3://jason-test-workspace/pbmc3k.h5ad"
          ]
          ports:
          - containerPort: 8080
            protocol: TCP
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 500Mi 
              cpu: 250m
          readinessProbe: # Block traffic to container if not ready
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60 
            failureThreshold: 10
          livenessProbe: # Restart container if not healthy
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 600  # 10min
            periodSeconds: 3600 # 1hr
            failureThreshold: 2
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom: 
              secretKeyRef:
                name: cellxgene-creds
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom: 
              secretKeyRef:
                name: cellxgene-creds
                key: aws_secret_access_key
      # run on big memory machine
      nodeSelector:
        eks.amazonaws.com/nodegroup: eks-cellxgene
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "eks-cellxgene"
          effect: "NoSchedule"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cellxgene-deploy-2
  labels:
    app: cellxgene
    dataset: scRNA_rds_Ovarian_Malignant_cluster_object.h5ad
spec:
  replicas: 1
  selector:
    matchLabels:
      dataset: scRNA_rds_Ovarian_Malignant_cluster_object.h5ad
  template:
    metadata:
      labels:
        dataset: scRNA_rds_Ovarian_Malignant_cluster_object.h5ad
    spec:
      containers:
        - name: cellxgene-app2
          image: 'edit01/cellxgene:1.2.0'
          command: ["cellxgene"]
          args: [
            "launch",
            "-p",
            "8080",
            "--host",
            "0.0.0.0",
            "--backed",
            "--disable-annotations",
            "--disable-gene-sets-save",
            "s3://jason-test-workspace/scRNA_rds_Ovarian_Malignant_cluster_object.h5ad"
          ]
          ports:
          - containerPort: 8080
            protocol: TCP
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 2Gi
              cpu: 250m
          readinessProbe: # Block traffic to container if not ready
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            failureThreshold: 10
          livenessProbe: # Restart container if not healthy
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 600  # 10min
            periodSeconds: 3600 # 1hr
            failureThreshold: 2
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: cellxgene-creds
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: cellxgene-creds
                key: aws_secret_access_key
      # run on big memory machine
      nodeSelector:
        eks.amazonaws.com/nodegroup: eks-cellxgene
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "eks-cellxgene"
          effect: "NoSchedule"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cellxgene-deploy-3
  labels:
    app: cellxgene
    dataset: scRNA_rds_Ovarian_nonMalignant_cluster_object.h5ad
spec:
  replicas: 1
  selector:
    matchLabels:
      dataset: scRNA_rds_Ovarian_nonMalignant_cluster_object.h5ad
  template:
    metadata:
      labels:
        dataset: scRNA_rds_Ovarian_nonMalignant_cluster_object.h5ad
    spec:
      containers:
        - name: cellxgene-app3
          image: 'edit01/cellxgene:1.2.0'
          command: ["cellxgene"]
          args: [
            "launch",
            "-p",
            "8080",
            "--host",
            "0.0.0.0",
            "--backed",
            "--disable-annotations",
            "--disable-gene-sets-save",
            "s3://jason-test-workspace/scRNA_rds_Ovarian_nonMalignant_cluster_object.h5ad"
          ]
          ports:
          - containerPort: 8080
            protocol: TCP
          imagePullPolicy: Always
          resources:
            limits:
              memory: 2Gi
              cpu: 250m
          readinessProbe: # Block traffic to container if not ready
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            failureThreshold: 10
          livenessProbe: # Restart container if not healthy
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 600  # 10min
            periodSeconds: 3600 # 1hr
            failureThreshold: 2
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: cellxgene-creds
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: cellxgene-creds
                key: aws_secret_access_key
      # run on big memory machine
      nodeSelector:
        eks.amazonaws.com/nodegroup: eks-cellxgene
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "eks-cellxgene"
          effect: "NoSchedule"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cellxgene-deploy-4
  labels:
    app: cellxgene
    dataset: Q3_norm_all_batch_reduced_meta_1.h5ad
spec:
  replicas: 1
  selector:
    matchLabels:
      dataset: Q3_norm_all_batch_reduced_meta_1.h5ad
  template:
    metadata:
      labels:
        dataset: Q3_norm_all_batch_reduced_meta_1.h5ad
    spec:
      containers:
        - name: cellxgene-app4
          image: 'edit01/cellxgene:1.2.0'
          command: ["cellxgene"]
          args: [
            "launch",
            "-p",
            "8080",
            "--host",
            "0.0.0.0",
            "--backed",
            "--disable-annotations",
            "--disable-gene-sets-save",
            "s3://jason-test-workspace/Q3_norm_all_batch_reduced_meta_1.h5ad"
          ]
          ports:
          - containerPort: 8080
            protocol: TCP
          imagePullPolicy: Always
          resources:
            limits:
              memory: 256Mi
              cpu: 250m
          readinessProbe: # Block traffic to container if not ready
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            failureThreshold: 10
          livenessProbe: # Restart container if not healthy
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 600  # 10min
            periodSeconds: 3600 # 1hr
            failureThreshold: 2
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: cellxgene-creds
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: cellxgene-creds
                key: aws_secret_access_key
      # run on big memory machine
      nodeSelector:
        eks.amazonaws.com/nodegroup: eks-cellxgene
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "eks-cellxgene"
          effect: "NoSchedule"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cellxgene-deploy-5
  labels:
    app: cellxgene
    dataset: BTC_GBM_001.h5ad
spec:
  replicas: 1
  selector:
    matchLabels:
      dataset: BTC_GBM_001.h5ad
  template:
    metadata:
      labels:
        dataset: BTC_GBM_001.h5ad
    spec:
      containers:
        - name: cellxgene-app5
          image: 'edit01/cellxgene:1.2.0'
          command: ["cellxgene"]
          args: [
            "launch",
            "-p",
            "8080",
            "--host",
            "0.0.0.0",
            "--backed",
            "--disable-annotations",
            "--disable-gene-sets-save",
            "s3://jason-test-workspace/BTC_GBM_001.h5ad"
          ]
          ports:
          - containerPort: 8080
            protocol: TCP
          imagePullPolicy: Always
          resources:
            limits:
              memory: 256Mi
              cpu: 250m
          readinessProbe: # Block traffic to container if not ready
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            failureThreshold: 10
          livenessProbe: # Restart container if not healthy
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 600  # 10min
            periodSeconds: 3600 # 1hr
            failureThreshold: 2
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: cellxgene-creds
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: cellxgene-creds
                key: aws_secret_access_key
      # run on big memory machine
      nodeSelector:
        eks.amazonaws.com/nodegroup: eks-cellxgene
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "eks-cellxgene"
          effect: "NoSchedule"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cellxgene-deploy-6
  labels:
    app: cellxgene
    dataset: BTC_GBM_002.h5ad
spec:
  replicas: 1
  selector:
    matchLabels:
      dataset: BTC_GBM_002.h5ad
  template:
    metadata:
      labels:
        dataset: BTC_GBM_002.h5ad
    spec:
      containers:
        - name: cellxgene-app6
          image: 'edit01/cellxgene:1.2.0'
          command: ["cellxgene"]
          args: [
            "launch",
            "-p",
            "8080",
            "--host",
            "0.0.0.0",
            "--backed",
            "--disable-annotations",
            "--disable-gene-sets-save",
            "s3://jason-test-workspace/BTC_GBM_002.h5ad"
          ]
          ports:
          - containerPort: 8080
            protocol: TCP
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: 250m
          readinessProbe: # Block traffic to container if not ready
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            failureThreshold: 10
          livenessProbe: # Restart container if not healthy
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 600  # 10min
            periodSeconds: 3600 # 1hr
            failureThreshold: 2
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: cellxgene-creds
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: cellxgene-creds
                key: aws_secret_access_key
      # run on big memory machine
      nodeSelector:
        eks.amazonaws.com/nodegroup: eks-cellxgene
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "eks-cellxgene"
          effect: "NoSchedule"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cellxgene-deploy-7
  labels:
    app: cellxgene
    dataset: BTC_GBM_003.h5ad
spec:
  replicas: 1
  selector:
    matchLabels:
      dataset: BTC_GBM_003.h5ad
  template:
    metadata:
      labels:
        dataset: BTC_GBM_003.h5ad
    spec:
      containers:
        - name: cellxgene-app7
          image: 'edit01/cellxgene:1.2.0'
          command: ["cellxgene"]
          args: [
            "launch",
            "-p",
            "8080",
            "--host",
            "0.0.0.0",
            "--backed",
            "--disable-annotations",
            "--disable-gene-sets-save",
            "s3://jason-test-workspace/BTC_GBM_003.h5ad"
          ]
          ports:
          - containerPort: 8080
            protocol: TCP
          imagePullPolicy: Always
          resources:
            limits:
              memory: 256Mi
              cpu: 250m
          readinessProbe: # Block traffic to container if not ready
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            failureThreshold: 10
          livenessProbe: # Restart container if not healthy
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 600  # 10min
            periodSeconds: 3600 # 1hr
            failureThreshold: 2
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: cellxgene-creds
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: cellxgene-creds
                key: aws_secret_access_key
      # run on big memory machine
      nodeSelector:
        eks.amazonaws.com/nodegroup: eks-cellxgene
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "eks-cellxgene"
          effect: "NoSchedule"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cellxgene-deploy-8
  labels:
    app: cellxgene
    dataset: gbm_filtered_processing2.h5ad
spec:
  replicas: 1
  selector:
    matchLabels:
      dataset: gbm_filtered_processing2.h5ad
  template:
    metadata:
      labels:
        dataset: gbm_filtered_processing2.h5ad
    spec:
      containers:
        - name: cellxgene-app8
          image: 'edit01/cellxgene:1.2.0'
          command: ["cellxgene"]
          args: [
            "launch",
            "-p",
            "8080",
            "--host",
            "0.0.0.0",
            "--backed",
            "--disable-annotations",
            "--disable-gene-sets-save",
            "--gene-sets-file",
            "/genesets/gbm_filtered_processing2_fixed_genesets.csv",
            "s3://jason-test-workspace/gbm_filtered_processing2_fixed.h5ad"
          ]
          ports:
          - containerPort: 8080
            protocol: TCP
          imagePullPolicy: Always
          # resources:
          #   limits:
          #     memory: 7Gi
          #     cpu: 250m
          readinessProbe: # Block traffic to container if not ready
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            failureThreshold: 10
          livenessProbe: # Restart container if not healthy
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 600  # 10min
            periodSeconds: 3600 # 1hr
            failureThreshold: 2
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: cellxgene-creds
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: cellxgene-creds
                key: aws_secret_access_key
      # run on big memory machine
      nodeSelector:
        eks.amazonaws.com/nodegroup: eks-cellxgene
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "eks-cellxgene"
          effect: "NoSchedule"
---
kind: Service
apiVersion: v1
metadata:
  name: cellxgene-service-1
  labels:  # For convenience
    app: cellxgene
    dataset: pbmc3k.h5ad
spec:
  selector:
    dataset: pbmc3k.h5ad
  ports:
    - port: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: cellxgene-service-2
  labels:  # For convenience
    app: cellxgene
    dataset: scRNA_rds_Ovarian_Malignant_cluster_object.h5ad
spec:
  selector:
    dataset: scRNA_rds_Ovarian_Malignant_cluster_object.h5ad
  ports:
    - port: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: cellxgene-service-3
  labels:  # For convenience
    app: cellxgene
    dataset: scRNA_rds_Ovarian_nonMalignant_cluster_object.h5ad
spec:
  selector:
    dataset: scRNA_rds_Ovarian_nonMalignant_cluster_object.h5ad
  ports:
    - port: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: cellxgene-service-4
  labels:  # For convenience
    app: cellxgene
    dataset: Q3_norm_all_batch_reduced_meta_1.h5ad
spec:
  selector:
    dataset: Q3_norm_all_batch_reduced_meta_1.h5ad
  ports:
    - port: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: cellxgene-service-5
  labels:  # For convenience
    app: cellxgene
    dataset: BTC_GBM_001.h5ad
spec:
  selector:
    dataset: BTC_GBM_001.h5ad
  ports:
    - port: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: cellxgene-service-6
  labels:  # For convenience
    app: cellxgene
    dataset: BTC_GBM_002.h5ad
spec:
  selector:
    dataset: BTC_GBM_002.h5ad
  ports:
    - port: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: cellxgene-service-7
  labels:  # For convenience
    app: cellxgene
    dataset: BTC_GBM_003.h5ad
spec:
  selector:
    dataset: BTC_GBM_003.h5ad
  ports:
    - port: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: cellxgene-service-8
  labels:  # For convenience
    app: cellxgene
    dataset: gbm_filtered_processing2.h5ad
spec:
  selector:
    dataset: gbm_filtered_processing2.h5ad
  ports:
    - port: 8080
