apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cbioportal-backend-preview-set
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: cBioPortal
          repo: cbioportal
        requeueAfterSeconds: 60
  template:
    metadata:
      name: 'cbioportal-backend-preview-{{number}}'
    spec:
      destination:
        namespace: 'cbioportal-backend-preview-{{branch}}'
        server: 'https://kubernetes.default.svc'
      project: cbioportal-preview
      source:
        repoURL: https://github.com/knowledgesystems/knowledgesystems-k8s-deployment
        path: argocd/aws/203403084713/clusters/cbioportal-prod/apps/cbioportal-backend-preview/helm
        targetRevision: HEAD
        helm:
          parameters:
            - name: name
              value: cbioportal-backend-preview
            - name: namespace
              value: 'cbioportal-backend-preview-{{branch}}'
            - name: imageTag
              value: 2979b0c838af9ceee67cc85e7b84f6b210918696-web-shenandoah
      syncPolicy:
        automated:
          selfHeal: true