apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  labels:
    run: oncokb-transcript
  name: oncokb-transcript
spec:
  replicas: 1
  selector:
    matchLabels:
      run: oncokb-transcript
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: oncokb-transcript
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod,api-docs,no-liquibase
            - name: APPLICATION_REDIS_ENABLED
              value: "false"
            - name: APPLICATION_REDIS_TYPE
              value: "$(REDIS_TYPE)"
            - name: APPLICATION_REDIS_ADDRESS
              value: "$(REDIS_ADDRESS)"
            - name: APPLICATION_REDIS_PASSWORD
              value: "$(REDIS_PASSWORD)"
            - name: SPRING_DATASOURCE_URL
              value: "$(DB_URL)/oncokb_transcript"
            - name: SPRING_DATASOURCE_USERNAME
              value: "$(DB_USERNAME)"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "$(DB_PASSWORD)"
          envFrom:
            - secretRef:
                name: oncokb-transcript
            - secretRef:
                name: oncokb-db-msk-dev-rds
            - secretRef:
                name: oncokb-redis-cluster
          image: oncokb/oncokb-transcript:0.9.4
          imagePullPolicy: Always
          # use actionable variant endpoint to cache everything
          readinessProbe:
            httpGet:
              path: /
              port: 9090
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 9090
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 3000
          name: oncokb-transcript
          ports:
            - name: http
              containerPort: 9090
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      nodeSelector:
        workload: lg-general
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "lg-general"
          effect: "NoSchedule"
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: oncokb-transcript
spec:
  ports:
    - port: 9090
      name: http
      targetPort: 9090
  selector:
    run: oncokb-transcript
  type: ClusterIP
