apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: oncokb-cronjob-daily-usage-analysis-cronjob
  namespace: oncokb
spec:
  schedule: "0 6 * * 6"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - envFrom:
            - configMapRef:
                name: aws-cli-credentials
            - configMapRef:
                name: oncokb-usage-analysis-config
            name: main
            image: oncokb/oncokb-usage-analysis:0.1.0
            command: ["/bin/bash", "-c"]
            args:
              - python3 src/main.py
          restartPolicy: Never
