# THIS CRONJOB IS NOT IN PRODUCTION

apiVersion: batch/v1
kind: CronJob
metadata:
  name: oncokb-cronjob-daily-usage-analysis-cronjob
  namespace: oncokb
spec:
  schedule: "0 12 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - envFrom:
            - configMapRef:
                name: aws-cli-credentials
            - configMapRef:
                name: oncokb-usage-analysis-config
            name: main
            image: oncokb/oncokb-usage-analysis:0.1.9
            command: ["/bin/bash", "-c"]
            args:
              - cd src;
                python3 main.py;
          restartPolicy: Never
