apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: oncokb-cronjob-daily-backup-public-website-db
  namespace: oncokb
spec:
  # this would trigger the run on 4pm EDT
  schedule: "0 20 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - envFrom:
            - configMapRef:
                name: aws-cli-credentials
            - configMapRef:
                name: oncokb-public
            - configMapRef:
                name: oncokb-db-genie-rds
            name: main
            image: mysql:5.7
            command: ["/bin/sh", "-c"]
            args:
              - echo "Install python";
                apt update; apt install python3 -y;
                echo "Done installing python\n\n";

                echo "Install pip3";
                apt install python3-pip -y;
                echo "Done installing pip3\n\n";

                echo "Install AWS CLI";
                pip3 install awscli --upgrade;
                echo "Done installing AWS CLI\n\n";

                echo "Configure AWS CLI";
                aws configure set aws_access_key_id ${ACCESS_KEY_ID};
                aws configure set aws_secret_access_key ${SECRET_ACCESS_KEY};
                aws configure set default.region ${AWS_REGION};
                echo "Done configuring AWS CLI\n\n";

                DB_HOST=$(echo "${DB_URL}" | sed -e's,^.*://\(.*\),\1,g' | cut -d":" -f1)
                FILE_NAME=schema_$(date "+%m-%d-%Y-%H-%M-%S").sql.gz;
                echo "Dump public database schema";
                mysqldump -h${DB_HOST} -u${DB_USERNAME} -p${DB_PASSWORD} oncokb_public -d --no-tablespaces | gzip > ${FILE_NAME};
                echo "Done dumping database schema";
                echo "Move the schema to s3 ";
                aws s3api put-object --bucket oncokb --key public-website/database/backup/${FILE_NAME} --body ${FILE_NAME};
                echo "Done moving the database schema\n\n";

                FILE_NAME=data_$(date "+%m-%d-%Y-%H-%M-%S").sql.gz;
                echo "Dump public database data except token stats";
                mysqldump -h${DB_HOST} -u${DB_USERNAME} -p${DB_PASSWORD} oncokb_public --ignore-table=oncokb_public.token_stats --compact --no-create-info --no-tablespaces | gzip > ${FILE_NAME};
                echo "Done dumping database data";
                echo "Move the data to s3 ";
                aws s3api put-object --bucket oncokb --key public-website/database/backup/${FILE_NAME} --body ${FILE_NAME};
                echo "Done moving the database dump\n\n";
          restartPolicy: Never
