apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: oncokb-cronjob-clinical-trials-daily-matching
  namespace: oncokb
spec:
  schedule: "0 13 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - envFrom:
            - configMapRef:
                name: clinical-trials-matching-config
            - configMapRef:
                name: aws-cli-credentials
            name: main
            image: oncokb/clinical-trials-matching-pipeline:0.1.1
            args:
            - /bin/bash
            - -c
            - date; python3 /code/scripts/main.py
          restartPolicy: Never
