apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: null
  generation: 1
  labels:
    run: eks-immunotherapy
  name: eks-immunotherapy
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/eks-immunotherapy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: eks-immunotherapy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: eks-immunotherapy
    spec:
      volumes:
      - name: immunotherapy-eks-configmap-volume
        configMap:
          name: cbioportal-immunotherapy-kc
          items:
          - key: portal.properties
            path: portal.properties
          - key: immunotherapy-cbioportal-saml-idp-metadata.xml
            path: immunotherapy-cbioportal-saml-idp-metadata.xml
          - key: cbioportal-saml-keystore.jks
            path: cbioportal-saml-keystore.jks
      containers:
      - envFrom:
        - configMapRef:
            name: immunotherapy-eks
        env:
        - name: PORTAL_HOME
          value: /cbioportal/
        image: cbioportal/cbioportal:3.7.4-redis-web-shenandoah
        volumeMounts:
        - name: immunotherapy-eks-configmap-volume
          mountPath: /cbioportal/portal.properties
          subPath: portal.properties
        - name: immunotherapy-eks-configmap-volume
          mountPath: /cbioportal/immunotherapy-cbioportal-saml-idp-metadata.xml
          subPath: immunotherapy-cbioportal-saml-idp-metadata.xml
        - name: immunotherapy-eks-configmap-volume
          mountPath: /cbioportal/cbioportal-saml-keystore.jks
          subPath: cbioportal-saml-keystore.jks
        command: [ "/usr/bin/java" ]
        args: [
            # from https://developers.redhat.com/blog/2017/04/04/openjdk-and-containers/
            "-Xms100m",
            "-Xmx15g",
            "-XX:+UnlockExperimentalVMOptions",
            "-XX:+UseShenandoahGC",
            "-XX:ShenandoahUncommitDelay=1000",
            "-XX:ShenandoahGuaranteedGCInterval=10000",
            #"-XX:+AlwaysPreTouch",
            #"-XX:+UseTransparentHugePages",
            #"-XX:+UseNUMA",
            #"-XX:+PrintGCDetails",
            #"-XX:+UseParallelGC",
            #"-XX:+PrintGCDateStamps",
            #"-XX:ParallelGCThreads=4",
            #"-XX:+UseG1GC",
            #"-XX:+AggressiveHeap",
            # non aggressive garbage collection
            #"-XX:MinHeapFreeRatio=20",
            #"-XX:MaxHeapFreeRatio=40",
            #"-XX:GCTimeRatio=19",
            #"-XX:AdaptiveSizePolicyWeight=90",
            # This issue says to use maxRAMFraction > 1
            # https://github.com/akka/akka/issues/23499, but haven't found this
            # to work v well
            #"-XX:MaxRAMFraction=1",
            "-XX:+PrintFlagsFinal",
            "-XshowSettings:vm",
            # need to set MaxRAM, somehow the MaxRAMFraction is not picked up
            # from the limits
            #"-XX:MaxRAM=6500m",
            # enable remote debug
            "-Dabout=about_us.html",
            "-Dnews=news_tcga.html",
            "-Dfaq=faq_tcga.html",
            "-Dfilter_groups_by_appname=false",
            "-Dcom.sun.management.jmxremote.rmi.port=8849",
            "-Dcom.sun.management.jmxremote=false",
            "-Dcom.sun.management.jmxremote.port=8849",
            "-Dcom.sun.management.jmxremote.ssl=false",
            "-Dcom.sun.management.jmxremote.authenticate=false",
            "-Dcom.sun.management.jmxremote.local.only=false",
            "-Djava.rmi.server.hostname=localhost",
            "-Dquick_search.enabled=false",
            "-Dskin.footer=",
            "-Dskin.right_nav.whats_new_blurb=",
            "-Dskin.example_study_queries=tcga pancancer atlas\ntcga -legacy -pancancer\ntcga or icgc\nmsk-impact\n-\"cell line\"\nbreast\nesophageal OR stomach\nprostate msk\nserous",
            "-Dpriority_studies=",
            "-Dskin.patientview.filter_genes_profiled_all_samples=false",
            "-Dinstallation_map_url=https://installationmap.netlify.app/",
            "-Dapp.name=eks-immunotherapy",
            # connecting over dbcp
            "-Ddbconnector=dbcp",
            "-Dauthenticate=saml",
            "-Dauthorization=false",
            "-Ddb.user=$(DB_USER)",
            "-Ddb.password=$(DB_PASSWORD)",
            "-Ddb.host=$(DB_HOST)",
            "-Ddb.connection_string=$(DB_CONNECTION_STRING)",
            "-Ddb.portal_db_name=cgds_gdac",
            "-Ddb.suppress_schema_version_mismatch_errors=true",
            #"-Dtomcat.catalina.scope=runtime",
            "-Dshow.transcript_dropdown=true",
            "-Dshow.civic=$(SHOW_CIVIC)",
            "-Dskin.show_tweet_button=$(SKIN_SHOW_TWEET_BUTTON)",
            "-Dskin.email_contact=cbioportal@googlegroups.com",
            "-Dskin.data_sets_footer=The data sets in the portal are related to immunotherapy research.",
            "-Dskin.data_sets_header=The portal currently contains data from the following cancer genomics studies. The table below lists the number of available samples per study and data type.",
            "-Dskin.examples_right_column_html=<ul>  <li>    <a href=\"index.do?tab_index=tab_visualize&cancer_study_list=coadread_tcga_pub&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_nonhypermut&case_ids=&gene_list=KRAS+NRAS+BRAF&gene_set_choice=user-defined-list&Action=Submit\">RAS/RAF alterations in colorectal cancer</a>  </li>  <li>    <a href=\"index.do?tab_index=tab_visualize&cancer_study_list=ov_tcga_pub&cancer_study_id=ov_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=ov_tcga_pub_mutations&Z_SCORE_THRESHOLD=2.0&case_set_id=ov_tcga_pub_3way_complete&case_ids=&gene_list=BRCA1+BRCA2&gene_set_choice=user-defined-list&Action=Submit#mutation_details\">BRCA1 and BRCA2 mutations in ovarian cancer</a>  </li>  <li>    <a href=\"index.do?cancer_study_list=ucec_tcga_pub&cancer_study_id=ucec_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=ucec_tcga_pub_mutations&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=ucec_tcga_pub_sequenced&case_ids=&gene_set_choice=user-defined-list&gene_list=POLE%3A+MUT+%3D+P286+MUT+%3D+V411+MUT+%3D+L424+MUT+%3D+S297F&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit\">POLE hotspot mutations in endometrial cancer</a>  </li>  <li>    <a href=\"index.do?case_set_id=gbm_tcga_pub_sequenced&tab_index=tab_visualize&Action=Submit&genetic_profile_ids=gbm_tcga_pub_mutations&genetic_profile_ids=gbm_tcga_pub_cna_rae&case_ids=&Z_SCORE_THRESHOLD=1.0&cancer_study_list=gbm_tcga_pub&cancer_study_id=gbm_tcga_pub&gene_list=TP53+MDM2+MDM4&gene_set_choice=user-defined_list&Action=Submit#summary\">TP53 and MDM2/4 alterations in GBM</a>  </li>  <li>    <a href=\"index.do?case_set_id=gbm_tcga_pub_sequenced&tab_index=tab_download&Action=Submit&genetic_profile_ids=gbm_tcga_pub_mutations&cancer_study_list=gbm_tcga_pub&cancer_study_id=gbm_tcga_pub&gene_list=PTEN&gene_set_choice=user-defined_list&transpose_matrix=on\">PTEN mutations in GBM in text format</a>  </li>  <li>    <a href=\"ln?q=BRAF:MUT=V600E\">BRAF V600E mutations across cancer types</a>  </li>  <li>    <a href=\"case.do#/patient?studyId=ucec_tcga_pub&caseId=TCGA-BK-A0CC\">Patient view of an endometrial cancer case</a>  </li></ul>",
            "-Dskin.right_logo=mskcc_logo_3d_grey.jpg",
            "-Dskin.right_nav.show_testimonials=true",
            "-Dskin.title=cBioPortal for Immunotherapy",
            "-Dskin.authorization_message=Access to this portal is only available to authorized users only. [<a href=\"http://bit.ly/2f4hH1D\">Request Access</a>].",
            "-Dskin.blurb=<b>The cBioPortal for Immunotherapy hosts cancer immunotherapy datasets generated by the Immunogenomics and Precision Oncology Platform (IPOP) at MSK.</b>",
            "-Dshow.mdacc.heatmap=true",
            "-Dsession.service.url=https://session-service.cbioportal.aws.mskcc.org/api/sessions/immunotherapy_portal/",
            "-Dsession.service.origin=*",
            "-Dsession.service.user=$(SESSION_SERVICE_USER_NAME)",
            "-Dsession.service.password=$(SESSION_SERVICE_USER_PASSWORD)",
            "-Dgoogle_analytics_profile_id=$(GOOGLE_ANALYTICS_PROFILE_ID)",
            "-Dgoogleplus.consumer.key=$(GOOGLE_PLUS_CONSUMER_KEY)",
            "-Dgoogleplus.consumer.secret=$(GOOGLE_PLUS_CONSUMER_SECRET)",
            "-Dmicrosoftlive.consumer.key=$(MICROSOFT_LIVE_CONSUMER_KEY)",
            "-Dmicrosoftlive.consumer.secret=$(MICROSOFT_LIVE_CONSUMER_SECRET)",
            "-Dbitly.url=$(BITLY_URL)",
            "-Dbitly.access.token=$(BITLY_ACCESS_TOKEN)",
            "-Dsentry.dsn=$(SENTRY_DSN)",
            "-Dsentry.factory=org.cbioportal.logging.SentryClientFactory",
            #"-Dsentryjs.frontend_project_endpoint=$(SENTRY_FRONTEND_DSN)",
            "-Dsitemaps=true",
            "-Doncokb.public_api.url=https://www.oncokb.org/api/v1",
            "-Doncokb.token=$(ONCOKB_TOKEN)",
            "-Dgenomenexus.url=https://v1.genomenexus.org",
            "-Dmatchminer.url=http://ec2-54-158-52-176.compute-1.amazonaws.com:5555",
            "-Dmatchminer.token=$(MATCHMINER_TOKEN)",
            # cache settings (currently redis)
#            "-Dcache.statistics_endpoint_enabled=false",
            "-Dredis.database=14",
            "-Dpersistence.cache_type=redis",
            "-Dredis.leader_address=redis://cbioportal-persistence-redis-master:6379",
            "-Dredis.follower_address=redis://cbioportal-persistence-redis-master:6379",
            "-Dredis.password=$(REDIS_PASSWORD)",
            "-Dehcache.cache_type=none",
            "-Dcache.endpoint.api-key=$(CACHE_API_KEY)",
            "-Dcache.endpoint.enabled=true",
            "-Dredis.clear_on_startup=true",
            # misc frontend settings (this is NOT for backend persistence layer caching)
            "-Denable_persistent_cache=false",
            # compress on client side
            "-Denable_request_body_gzip_compression=true",
            "-jar",
            "/webapp-runner.jar",
            # this addresses same issue as
            # https://github.com/cBioPortal/cbioportal/issues/2328 one needs to
            # set this if one doesn't want to forward https -> http -> https
            # when logging in through google auth. Somehow this goes over http
            # otherwise.
            "--proxy-base-url",
            "https://immunotherapy.cbioportal.aws.mskcc.org:443",
            "--max-threads",
            "0",
            "--session-store",
            "redis",
            "--session-store-operation-timeout",
            "10000",
            # Fix long URL https://github.com/cBioPortal/cbioportal/issues/5836
            "-AmaxHttpHeaderSize=16384",
            "-AconnectionTimeout=20000",
            "--enable-compression",
            "--port",
            "8888",
            "/app.war"
        ]
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8888
          initialDelaySeconds: 45
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 180
          timeoutSeconds: 1
          periodSeconds: 12
          failureThreshold: 5
        name: eks-immunotherapy
        ports:
        - containerPort: 8888
          protocol: TCP
        - containerPort: 8849
          protocol: TCP
        resources:
          requests:
              memory: 2Gi
          limits:
              memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      # run on big memory machine
      nodeSelector:
        eks.amazonaws.com/nodegroup: msk-cbioportal
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: eks-immunotherapy
  name: eks-immunotherapy
  selfLink: /api/v1/namespaces/default/services/eks-immunotherapy
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8888
  selector:
    run: eks-immunotherapy
  type: ClusterIP
