apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: null
  generation: 1
  labels:
    run: eks-redirect-paired-bladder-2022
  name: eks-redirect-paired-bladder-2022
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/eks-redirect-paired-bladder-2022
spec:
  replicas: 1
  selector:
    matchLabels:
      run: eks-redirect-paired-bladder-2022
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: eks-redirect-paired-bladder-2022
    spec:
      containers:
      - image: morbz/docker-web-redirect:latest
        env:
        - name: REDIRECT_TARGET
          value: https://www.cbioportal.org/
        - name: REDIRECT_TYPE
          value: redirect
        command: [ "start.sh" ]
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 15
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 15
          failureThreshold: 3
        name: eks-redirect-paired-bladder-2022
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
              cpu: 50m
              memory: 8M
          limits:
              memory: 16M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      nodeSelector:
        eks.amazonaws.com/nodegroup: small-memory-portals
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: eks-redirect-paired-bladder-2022
  name: eks-redirect-paired-bladder-2022
  selfLink: /api/v1/namespaces/default/services/eks-redirect-paired-bladder-2022
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    run: eks-redirect-paired-bladder-2022
  type: ClusterIP
