controller:
  image:
    tag: v1.12.1
  service:
    annotations:
      last-update: 1692622798
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:084637913395:certificate/94428814-02ab-41ad-9848-43c7ac5e79de
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    targetPorts:
      https: 80