replicaCount: 1
global:
  librechat:
    existingSecretName: "librechat-credentials-env"
    existingSecretApiKey: ANTRHOPIC_API_KEY

librechat:
  existingSecretName: "librechat-credentials-env"
  existingConfigYaml: "librechat-config"

image:
  repository: cbioportal/cbioagent
  registry: docker.io
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "librechat-latest"

nodeSelector:
  workload: cbioagent

tolerations:
  - key: "workload"
    operator: "Equal"
    value: "cbioagent"
    effect: "NoSchedule"

ingress:
  enabled: false

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  timeoutSeconds: 1
  periodSeconds: 5
  failureThreshold: 3
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 20
  timeoutSeconds: 1
  periodSeconds: 12
  failureThreshold: 5
