apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cbioportal-backend-genie-public-blue
    tags.datadoghq.com/env: eks-genie-public
    tags.datadoghq.com/service: cbioportal
    tags.datadoghq.com/version: 6.1.0
  name: cbioportal-backend-genie-public-blue
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: cbioportal-backend-genie-public-blue
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        admission.datadoghq.com/java-lib.version: v1.24.2
      creationTimestamp: null
      labels:
        admission.datadoghq.com/enabled: "true"
        run: cbioportal-backend-genie-public-blue
        tags.datadoghq.com/env: eks-genie-public
        tags.datadoghq.com/service: cbioportal
        tags.datadoghq.com/version: 6.1.0
    spec:
      containers:
      - image: cbioportal/temp-genie-page:0.1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 12
          successThreshold: 1
          timeoutSeconds: 1
        name: cbioportal-backend-genie-public-blue
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 12
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        eks.amazonaws.com/nodegroup: eks-genie-cbioportal-ec2-test
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: eks-genie-cbioportal-ec2-test
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: cbioportal-backend-genie-public-blue
  name: cbioportal-backend-genie-public-blue
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: cbioportal-backend-genie-public-blue
  sessionAffinity: None
  type: ClusterIP
