apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: datadog
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: datadog
    app.kubernetes.io/version: "7"
    helm.sh/chart: datadog-3.109.2
  name: datadog-cluster-agent
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
      - nodes
      - namespaces
      - componentstatuses
      - limitranges
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - quota.openshift.io
    resources:
      - clusterresourcequotas
    verbs:
      - get
      - list
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resourceNames:
      - datadogtoken
      - datadogtoken
    resources:
      - configmaps
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resourceNames:
      - datadog-leader-election
      - datadog-leader-election
    resources:
      - configmaps
    verbs:
      - get
      - update
  - apiGroups:
      - coordination.k8s.io
    resourceNames:
      - datadog-leader-election
    resources:
      - leases
    verbs:
      - get
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
      - events
    verbs:
      - create
  - nonResourceURLs:
      - /version
      - /healthz
    verbs:
      - get
  - apiGroups:
      - ""
    resourceNames:
      - kube-system
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resourceNames:
      - datadog-cluster-id
    resources:
      - configmaps
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
      - persistentvolumeclaims
      - serviceaccounts
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - networkpolicies
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - autoscaling.k8s.io
    resources:
      - verticalpodautoscalers
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resourceNames:
      - datadog-webhook
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs:
      - get
      - list
      - watch
      - update
      - delete
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs:
      - create
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - replicasets
      - deployments
      - daemonsets
    verbs:
      - get
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - datadog-cluster-agent
      - hostnetwork
    resources:
      - securitycontextconstraints
    verbs:
      - use
