apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: oncokb-core-clinical-trials
  name: oncokb-core-clinical-trials
spec:
  replicas: 1
  selector:
    matchLabels:
      run: oncokb-core-clinical-trials
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: oncokb-core-clinical-trials
    spec:
      containers:
        - env:
          envFrom:
            - secretRef:
                name: oncokb-core
            - secretRef:
                name: oncokb-redis-cluster
            - secretRef:
                name: oncokb-db-msk-dev-rds
            - secretRef:
                name: aws-cli-credentials
          # The beta current is used to showcase a new search endpoint
          image: oncokb/oncokb:ct-alpha.3
          command: ["java"]
          args:
            [
              # from https://developers.redhat.com/blog/2017/04/04/openjdk-and-containers/
              "-Xms500m",
              "-XX:+UseSerialGC",
              # aggressive garbage collection
              "-XX:MinHeapFreeRatio=20",
              "-XX:MaxHeapFreeRatio=40",
              "-XX:GCTimeRatio=4",
              "-XX:AdaptiveSizePolicyWeight=90",
              "-XX:+UnlockExperimentalVMOptions",
              "-XX:+UseCGroupMemoryLimitForHeap",
              # use maxRAMFraction > 1 https://github.com/akka/akka/issues/23499
              "-XX:MaxRAMFraction=2",
              "-XX:+PrintFlagsFinal",
              "-XshowSettings:vm",
              # need to set MaxRAM, somehow the MaxRAMFraction is not picked up
              # from the limits
              "-XX:MaxRAM=2g",
              "-Dapp.name=$(APP_NAME)",
              "-Djdbc.driverClassName=com.mysql.jdbc.Driver",
              "-Djdbc.url=$(DB_URL)/oncokb_core_v4_7?useUnicode=yes&characterEncoding=UTF-8&useSSL=false",
              "-Djdbc.username=$(DB_USERNAME)",
              "-Djdbc.password=$(DB_PASSWORD)",
              "-Dgenomenexus.api=https://www.genomenexus.org/",
              "-Doncokb_transcript.token=$(ONCOKB_TRANSCRIPT_TOKEN)",
              "-Daws.s3.accessKey=$(ACCESS_KEY_ID)",
              "-Daws.s3.secretKey=$(SECRET_ACCESS_KEY)",
              "-Daws.s3.region=$(AWS_REGION)",
              "-Dredis.enable=false",
              "-Dredis.type=$(REDIS_TYPE)",
              "-Dredis.address=$(REDIS_ADDRESS)",
              "-Dredis.password=$(REDIS_PASSWROD)",
              "-Dredis.masterName=$(REDIS_MASTERNAME)",
              "-Dredis.expiration=$(REDIS_EXPIRATION)",
              "-Dshow_sitemaps=false",
              "-jar",
              "/webapp-runner.jar",
              "--enable-compression",
              "--port",
              "8888",
              "/app.war",
            ]
          imagePullPolicy: Always
          # use actionable variants endpoint to cache everything
          readinessProbe:
            httpGet:
              path: /api/v1/utils/allActionableVariants
              port: 8888
            initialDelaySeconds: 15
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /api/v1/utils/allActionableVariants
              port: 8888
            # wait for the pod is ready
            initialDelaySeconds: 600
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 20
          name: oncokb-core
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        workload: lg-general
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "lg-general"
          effect: "NoSchedule"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: oncokb-core-clinical-trials
  name: oncokb-core-clinical-trials
spec:
  ports:
    - port: 8888
  selector:
    run: oncokb-core-clinical-trials
  type: ClusterIP
