---
# Service account the client will use to delete a pod,
# by default the pods running inside the cluster can do no such things.
kind: ServiceAccount
apiVersion: v1
metadata:
  name: pod-deletion
  namespace: oncokb
---
# allow getting status and patching only the one deployment you want
# to restart
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-deletion
  namespace: oncokb
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete", "watch"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: ["get"]
---
# bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-deletion
  namespace: oncokb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-deletion
subjects:
  - kind: ServiceAccount
    name: pod-deletion
    namespace: oncokb