image:
  tag: "4.2"
nodeSelector:
  eks.amazonaws.com/nodegroup: cbio-session
persistence:
  size: 200Gi
tolerations:
  - effect: NoSchedule
    key: workload
    operator: Equal
    value: cbio-session