apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-persistent-volume
spec:
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-02fde1a565ddbaaf2
  capacity:
    storage: 200Gi
  storageClassName: gp2
  volumeMode: Filesystem