image:
  tag: "4.2"
nodeSelector:
  workload: cbio-session
persistence:
  size: 200Gi
  existingClaim: mongodb-persistent-volume-claim
tolerations:
  - effect: NoSchedule
    key: workload
    operator: Equal
    value: cbio-session
auth:
  existingSecret: cbioportal-session-service-mongodb-creds