---
# Service account the client will use to reset the deployment,
# by default the pods running inside the cluster can do no such things.
kind: ServiceAccount
apiVersion: v1
metadata:
  name: patch-deployment
---
# allow getting status and patching only the one deployment you want
# to restart
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patch-deployment
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", 'patch']
---
# bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-deployment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: patch-deployment
subjects:
  - kind: ServiceAccount
    name: patch-deployment
